owner: beedywool
repo: SplatApp-Status

sites:
  - name: SplatApp Client
    url: https://app.splatapp.ink
  - name: SplatApp Fileserver
    url: https://cdn.splatapp.ink/assets/img/appIcon.webp
  - name: SplatApp API
    url: https://api.splatapp.ink/health
  - name: SplatApp Demo
    url: https://demo.splatapp.ink
    port: 80
    check: "tcp-ping"
    ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: status.splatapp.ink
  baseUrl: /SplatApp-Status
  logoUrl: https://cdn.splatapp.ink/assets/img/appIcon.png
  name: SplatApp - Status
  introTitle: "**SplatApp Status Monitor**"
  introMessage: SplatApp Status Monitor
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
